spring:

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    username: root

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    password:
